using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using UnityEngine;

namespace EmployeeTraining.Localization
{
    public class LocalizationSerializer
	{
		private readonly string folderPath = Application.dataPath + "/CashierTraining";
		private readonly string fullFileName;
		private readonly Settings settings;

		public LocalizationSerializer(Plugin plugin)
		{
			this.settings = plugin.Settings;
			this.fullFileName = folderPath + "/Localization-2.0.0.json";
		}

		public StringLocalizer Load()
		{
			List<Localizations> list = null;
			if (this.settings.CustomizeLocalization)
			{
				if (!Directory.Exists(this.folderPath))
				{
					Directory.CreateDirectory(this.folderPath);
					list = this.Default();
				}
				if (File.Exists(this.fullFileName))
				{
					string value = File.ReadAllText(this.fullFileName);
					new JsonSerializerSettings();
					list = JsonConvert.DeserializeObject<List<Localizations>>(value);
				}
			}
			return new StringLocalizer(list ?? this.Default());
		}

		public void Write(List<Localizations> properties)
		{
			string contents = JsonConvert.SerializeObject(properties, Formatting.Indented);
			File.WriteAllText(this.fullFileName, contents);
		}

		public List<Localizations> Default()
		{
			List<Localizations> langs = new List<Localizations>() {
				new Localizations("en") {
					["Cashier Name"] = "Cashier {0}",
					["Restocker Name"] = "Restocker {0}",
					["Customer Helper Name"] = "Customer Helper {0}",
					["Security Guard Name"] = "Security Guard {0}",
					["Janitor Name"] = "Janitor {0}",
					["Lvl"] = "<size=70%>Lvl </size>{0}",
					["Popup Exp"] = "{0} Exp",
					["TRAINING"] = "TRAINING",
					["Cashiers"] = "Cashiers",
					["Restockers"] = "Restockers",
					["Customer Helpers"] = "<size=80%>Customer\nHelpers</size>",
					["Security Guards"] = "<size=80%>Security\nGuards</size>",
					["Janitors"] = "Janitors",
					["Exp."] = "Exp.",
					["Level"] = "Level {0} - {1}",
					["Scans Per Minute"] = "Scans per Minute",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Payment Time",
					["Payment Time Sec."] = "{0} sec.",
					["Daily Wage"] = "Daily Wage",
					["Rapidity"] = "Rapidity",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Capacity",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Dexterity",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Mastery Roadmap",
					["Rookie"] = "Rookie",
					["Middle"] = "Middle",
					["Advance"] = "Advanced",
					["Pro"] = "Pro",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Locked",
					["Approve"] = "Approve",
					["Defer"] = "Defer",
					["Train to Level Up"] = "Train to Level Up",
					["Unlock Higher Grade"] = "Unlock Higher Grade",
					["Show head gauge"] = "Show the gauge overhead",
					["Upgrade warning"] = "Would you promote {0}\nto the {1} grade?\n\nIt will be even more efficient but\nits daily wage will INCREASE to {2}</size>.",
					["NO CASHIERS HIRED"] = "NO CASHIERS HIRED",
					["NO RESTOCKERS HIRED"] = "NO RESTOCKERS HIRED",
					["NO CUSTOMER HELPERS HIRED"] = "NO CUSTOMER HELPERS HIRED",
					["NO SECURITY GUARDS HIRED"] = "NO SECURITY GUARDS HIRED",
					["NO JANITORS HIRED"] = "NO JANITORS HIRED",
				},
				new Localizations("ja-JP") {
					["Cashier Name"] = "レジ係 {0}",
					["Restocker Name"] = "補充係 {0}",
					["Customer Helper Name"] = "お客様対応係 {0}",
					["Security Guard Name"] = "警備員 {0}",
					["Janitor Name"] = "清掃員 {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["TRAINING"] = "トレーニング",
					["Cashiers"] = "レジ係",
					["Restockers"] = "補充係",
					["Customer Helpers"] = "<size=95%>お客様対応係</size>",
					["Security Guards"] = "警備員",
					["Janitors"] = "清掃員",
					["Exp."] = "EXP",
					["Level"] = "レベル {0} 【{1}】",
					["Scans Per Minute"] = "スキャン数毎分",
					["SPM Range"] = "{0} ～ {1}",
					["Payment Time"] = "支払い時間",
					["Payment Time Sec."] = "{0} 秒",
					["Daily Wage"] = "日給",
					["Rapidity"] = "素早さ",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "積載量",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "器用さ",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "上達ロードマップ",
					["Rookie"] = "初級",
					["Middle"] = "中級",
					["Advance"] = "上級",
					["Pro"] = "プロ",
					["?"] = "？",
					["Ninja"] = "ニンジャ",
					["Locked"] = "未解放",
					["Train to Level Up"] = "レベルアップまで訓練",
					["Unlock Higher Grade"] = "上位グレードを解放",
					["Approve"] = "承認",
					["Defer"] = "見送る",
					["Show head gauge"] = "頭上にゲージを表示する",
					["Upgrade warning"] = "{0} を『{1}グレード』に昇進させますか？\n\n手際は良くなりますが日給が {2}</size> に上がります。",
					["NO CASHIERS HIRED"] = "レジ係を雇っていません",
					["NO RESTOCKERS HIRED"] = "補充係を雇っていません",
					["NO CUSTOMER HELPERS HIRED"] = "お客様対応係を雇っていません",
					["NO SECURITY GUARDS HIRED"] = "警備員を雇っていません",
					["NO JANITORS HIRED"] = "清掃係を雇っていません",
				},
				new Localizations("it") { // イタリア
					["Cashier Name"] = "Cassiere: {0}",
					["Restocker Name"] = "Rifornitore {0}",
					["Customer Helper Name"] = "Assistente clienti {0}",
					["Security Guard Name"] = "Guardia di sicurezza {0}",
					["Janitor Name"] = "Custode {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} Exp",
					["TRAINING"] = "FORMAZIONE",
					["Cashiers"] = "Cassieri",
					["Restockers"] = "Rifornitori",
					["Customer Helpers"] = "<size=80%>Aiutanti del\ncliente</size>",
					["Security Guards"] = "<size=80%>Guardie di\nsicurezza</size>",
					["Janitors"] = "Custodi",
					["Exp."] = "Exp.",
					["Level"] = "Livello {0} - {1}",
					["Scans Per Minute"] = "Scansioni al minuto",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Tempo di pagamento",
					["Payment Time Sec."] = "{0} sec.",
					["Daily Wage"] = "Salario giornaliero",
					["Rapidity"] = "Rapidità",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Capacità",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Destrezza",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Tabella di marcia della maestria",
					["Rookie"] = "Principiante",
					["Middle"] = "Medio",
					["Advance"] = "Avanzato",
					["Pro"] = "Pro",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Bloccato",
					["Approve"] = "Approvare",
					["Defer"] = "Rimandalo",
					["Train to Level Up"] = "Treno per salire di liv.",
					["Unlock Higher Grade"] = "Sblocca il grado superiore",
					["Show head gauge"] = "Mostrare l'indicatore sulla testa",
					["Upgrade warning"] = "Promuovereste il {0}\nal grado {1}?\n\nSarà ancora più efficiente ma\nil suo stipendio giornaliero aumenterà a {2}</size>.",
					["NO CASHIERS HIRED"] = "NESSUN CASSIERE ASSUNTO",
					["NO RESTOCKERS HIRED"] = "NESSUN RIFORNITORE ASSUNTO",
					["NO CUSTOMER HELPERS HIRED"] = "NESSUN ASSISTENTE CLIENTI ASSUNTO",
					["NO SECURITY GUARDS HIRED"] = "NESSUN GUARDIE DI SICUREZZA ASSUNTA",
					["NO JANITORS HIRED"] = "NESSUN CUSTODI ASSUNTO",
				},
				new Localizations("fr-FR") { // フランス
					["Cashier Name"] = "Caissier {0}",
					["Restocker Name"] = "Réapprovisionneur {0}",
					["Customer Helper Name"] = "Assistant client {0}",
					["Security Guard Name"] = "Agent de sécurité {0}",
					["Janitor Name"] = "Agent d'entretien {0}",
					["Lvl"] = "<size=70%>Niv </size>{0}",
					["Popup Exp"] = "{0} XP",
					["Level"] = "Niveau {0} - {1}",
					["TRAINING"] = "Formation",
					["Cashiers"] = "Caissiers",
					["Restockers"] = "<size=80%>Réappro-\nvisionneurs</size>",
					["Customer Helpers"] = "<size=80%>Assistant\nclient</size>",
					["Security Guards"] = "<size=80%>Agents de\nsécurité</size>",
					["Janitors"] = "<size=80%>Agents\nd'entretien</size>",
					["Exp."] = "XP",
					["Scans Per Minute"] = "Scans par minute",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Temps de paiement",
					["Payment Time Sec."] = "{0} sec.",
					["Daily Wage"] = "Salaire journalier",
					["Rapidity"] = "Rapidité",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Capacité",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Dextérité",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Feuille de route de la maîtrise",
					["Rookie"] = "Débutant",
					["Middle"] = "Moyen",
					["Advance"] = "Progression",
					["Pro"] = "Pro",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Verrouillé",
					["Approve"] = "Approuver",
					["Defer"] = "Reporter",
					["Train to Level Up"] = "Passer au niv. suivant",
					["Unlock Higher Grade"] = "Débloquer le prochain",
					["Show head gauge"] = "Montrer la jauge au-dessus de la tête",
					["Upgrade warning"] = "Seriez-vous prêt à promouvoir le {0}\nau grade {1} ?\n\nIl sera encore plus efficace mais\nson salaire journalier passera à {2}</size>.",
					["NO CASHIERS HIRED"] = "PAS D'CAISSIERS EMBAUCHÉS",
					["NO RESTOCKERS HIRED"] = "PAS D'RESTOCKERS EMBAUCHÉS",
					["NO CUSTOMER HELPERS HIRED"] = "PAS D'ASSISTANT CLIENT EMBAUCHÉS",
					["NO SECURITY GUARDS HIRED"] = "PAS D'AGENTS DE SÉCURITÉ EMBAUCHÉS",
					["NO JANITORS HIRED"] = "PAS D'CONCIERGES EMBAUCHÉS",
				},
				new Localizations("pt-PT") { // ポルトガル
					["Cashier Name"] = "Caixa {0}",
					["Restocker Name"] = "Repositor {0}",
					["Customer Helper Name"] = "Ajudante do cliente {0}",
					["Security Guard Name"] = "Gauarda de segurança {0}",
					["Janitor Name"] = "Zelador {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} Exp",
					["Level"] = "Nível {0} - {1}",
					["TRAINING"] = "TREINAMENTO",
					["Cashiers"] = "Caixas",
					["Restockers"] = "Repositores",
					["Customer Helpers"] = "<size=80%>Ajudantes do\ncliente</size>",
					["Security Guards"] = "<size=80%>Guardas de\nsegurança</size>",
					["Janitors"] = "Zeladores",
					["Exp."] = "Exp",
					["Scans Per Minute"] = "Leituras por minuto",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Tempo de pagamento",
					["Payment Time Sec."] = "{0} seg.",
					["Daily Wage"] = "Salário diário",
					["Rapidity"] = "Rapidez",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Capacidade",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Destreza",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Roteiro de domínio",
					["Rookie"] = "Novato",
					["Middle"] = "Médio",
					["Advance"] = "Avançado",
					["Pro"] = "Pro",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "bloqueado",
					["Approve"] = "Aprovar",
					["Defer"] = "Adiar",
					["Train to Level Up"] = "Treinar para subir de nível",
					["Unlock Higher Grade"] = "Desbloquear grau superior",
					["Show head gauge"] = "Mostrar o medidor em cima",
					["Upgrade warning"] = "Promoveria o {0}\nao grau {1}?\n\nEle será ainda mais eficiente mas\no seu salário diário AUMENTARÁ para {2}</size>.",
					["NO CASHIERS HIRED"] = "NÃO FORAM CONTRATADOS CAIXAS",
					["NO RESTOCKERS HIRED"] = "NÃO FORAM CONTRATADOS REPOSITORES",
					["NO CUSTOMER HELPERS HIRED"] = "NÃO FORAM CONTRATADOS AJUDANTE DO CLIENTE",
					["NO SECURITY GUARDS HIRED"] = "NÃO FORAM CONTRATADOS GUARDAS DE SEGURANÇA",
					["NO JANITORS HIRED"] = "NÃO FORAM CONTRATADOS ZELADORES",
				},
				new Localizations("pt-BR") { // ブラジル・ポルトガル
					["Cashier Name"] = "Operador de caixa {0}",
					["Restocker Name"] = "Repositor {0}",
					["Customer Helper Name"] = "Assistente de Atendimento {0}",
					["Security Guard Name"] = "Segurança {0}",
					["Janitor Name"] = "Zelador {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} Exp",
					["Level"] = "Nível {0} - {1}",
					["TRAINING"] = "TREINAMENTO",
					["Cashiers"] = "<size=80%>Operadores de\ncaixa</size>",
					["Restockers"] = "Repositores",
					["Customer Helpers"] = "<size=80%>Assistentes de\nAtendimento</size>",
					["Security Guards"] = "Seguranças",
					["Janitors"] = "Zeladores",
					["Exp."] = "Exp",
					["Scans Per Minute"] = "Escaneamentos por minuto",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Tempo de pagamento",
					["Payment Time Sec."] = "{0} seg.",
					["Daily Wage"] = "Salário diário",
					["Rapidity"] = "Rapidez",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Capacidade",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Destreza",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Roteiro de domínio",
					["Rookie"] = "Novato",
					["Middle"] = "Médio",
					["Advance"] = "Avançado",
					["Pro"] = "Pro",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Bloqueado",
					["Approve"] = "Aprovar",
					["Defer"] = "Adiar",
					["Train to Level Up"] = "Treinar para subir de nível",
					["Unlock Higher Grade"] = "Desbloquear grau superior",
					["Show head gauge"] = "Mostrar o medidor na cabeça",
					["Upgrade warning"] = "Promoveria o {0}\nao grau {1}?\n\nEle será ainda mais eficiente mas\no seu salário diário AUMENTARÁ para {2}</size>.",
					["NO CASHIERS HIRED"] = "NENHUM CAIXA CONTRATADO",
					["NO RESTOCKERS HIRED"] = "NENHUM REPOSITOR CONTRATADO",
					["NO CUSTOMER HELPERS HIRED"] = "NENHUM AJUDANTE DO CLIENTE CONTRATADO",
					["NO SECURITY GUARDS HIRED"] = "NENHUM GUARDAS DE SEGURANÇA CONTRATADO",
					["NO JANITORS HIRED"] = "NENHUM ZELADORES CONTRATADO",
				},
				new Localizations("de") { // ドイツ
					["Cashier Name"] = "Kassierer {0}",
					["Restocker Name"] = "Auffüller {0}",
					["Customer Helper Name"] = "Kundenhelfer {0}",
					["Security Guard Name"] = "Sicherheitskraft {0}",
					["Janitor Name"] = "Hausmeister {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EP",
					["Level"] = "Stufe {0} - {1}",
					["TRAINING"] = "Ausbildung",
					["Cashiers"] = "Kassierer",
					["Restockers"] = "Auffüller",
					["Customer Helpers"] = "<size=80%>Kunden-\nbetreuer</size>",
					["Security Guards"] = "<size=80%>Sicherheits-\npersonal</size>",
					["Janitors"] = "<size=80%>Reinigungs-\nkräfte</size>",
					["Exp."] = "EP",
					["Scans Per Minute"] = "Scans pro Minute",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Zahlungszeit",
					["Payment Time Sec."] = "{0} Sek.",
					["Daily Wage"] = "Täglicher Lohn",
					["Rapidity"] = "Zügigkeit",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Tragfähigkeit",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Fingerfertigkeit",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Mastery-Fahrplan",
					["Rookie"] = "Neueinsteiger",
					["Middle"] = "Mittel",
					["Advance"] = "Fortgeschritten",
					["Pro"] = "Profi",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Gesperrt",
					["Approve"] = "Genehmigen",
					["Defer"] = "Aufschieben",
					["Train to Level Up"] = "Trainieren, um aufzusteigen",
					["Unlock Higher Grade"] = "Obere Stufe freischalten",
					["Show head gauge"] = "Zeigen Sie das Messgerät über dem Kopf",
					["Upgrade warning"] = "Würden Sie {0}\nzum {1} grad befördern?\n\nEr wird noch effizienter sein aber\nsein Tageslohn wird auf {2}</size> ERHÖHT.",
					["NO CASHIERS HIRED"] = "KEINE KASSIERER EINGESTELLT",
					["NO RESTOCKERS HIRED"] = "KEINE AUFFÜLLER EINGESTELLT",
					["NO CUSTOMER HELPERS HIRED"] = "KEINE KUNDENHELFER EINGESTELLT",
					["NO SECURITY GUARDS HIRED"] = "KEINE SICHERHEITSLEUTE EINGESTELLT",
					["NO JANITORS HIRED"] = "KEINE HAUSMEISTER EINGESTELLT",
				},
				new Localizations("da-DK") { // デンマーク
					["Cashier Name"] = "Kassemedarbejder {0}",
					["Restocker Name"] = "Lagermedarbejder {0}",
					["Customer Helper Name"] = "Kundemedhjælper {0}",
					["Security Guard Name"] = "Sikkerhedsvagt {0}",
					["Janitor Name"] = "Pedel {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["Level"] = "Niveau {0} - {1}",
					["TRAINING"] = "Uddannelse",
					["Cashiers"] = "<size=80%>Kasse-\nmedarbejdere</size>",
					["Restockers"] = "<size=80%>Lager-\nmedarbejdere</size>",
					["Customer Helpers"] = "<size=80%>Kunde-\nmedhjælpere</size>",
					["Security Guards"] = "<size=80%>Sikkerheds-\nvagter</size>",
					["Janitors"] = "Pedel",
					["Exp."] = "EXP",
					["Scans Per Minute"] = "Scanninger pr. minut",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Tid til betaling",
					["Payment Time Sec."] = "{0} sek.",
					["Daily Wage"] = "Daglig løn",
					["Rapidity"] = "Fodhastighed",
					["Speed"] = "{0}<size=70%> km/t</size>",
					["Capacity"] = "Kapacitet",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Fingerfærdighed",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Køreplan for mestring",
					["Rookie"] = "Rookie",
					["Middle"] = "Mellem",
					["Advance"] = "Fremskreden",
					["Pro"] = "Pro",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Låst",
					["Approve"] = "Godkend",
					["Defer"] = "Udsæt",
					["Train to Level Up"] = "Træn for at stige i niveau",
					["Unlock Higher Grade"] = "Lås op for øvre niveau",
					["Show head gauge"] = "Vis måleren over hovedet",
					["Upgrade warning"] = "Vil du forfremme {0}\ntil {1} klassen?\n\nDen vil være endnu mere effektiv men\ndens daglige løn vil STIGE til {2}</size>.",
					["NO CASHIERS HIRED"] = "INGEN KASSEMEDARBEJDERE ANSAT",
					["NO RESTOCKERS HIRED"] = "INGEN LAGERMEDARBEJDERE ANSAT",
					["NO CUSTOMER HELPERS HIRED"] = "INGEN KUNDEMEDHJÆLPERE ANSAT",
					["NO SECURITY GUARDS HIRED"] = "INGEN SIKKERHEDSVAGTER ANSAT",
					["NO JANITORS HIRED"] = "INGEN PEDEL ANSAT",
				},
				new Localizations("pl-PL") { // ポーランド
					["Cashier Name"] = "Kasjer {0}",
					["Restocker Name"] = "Magazynier {0}",
					["Customer Helper Name"] = "Pomocnik klienta {0}",
					["Security Guard Name"] = "Pracownik ochrony {0}",
					["Janitor Name"] = "Sprzątacz {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["Level"] = "Poziom {0} - {1}",
					["TRAINING"] = "SZKOLENIE",
					["Cashiers"] = "Kasjerzy",
					["Restockers"] = "<size=85%>Magazynierzy</size>",
					["Customer Helpers"] = "<size=80%>Wsparcie\nklienta</size>",
					["Security Guards"] = "<size=80%>Pracownicy\nochrony</size>",
					["Janitors"] = "Sprzątacze",
					["Exp."] = "EXP",
					["Scans Per Minute"] = "Skany na minutę",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Czas płatności",
					["Payment Time Sec."] = "{0} sek.",
					["Daily Wage"] = "Dzienne wynagrodzenie",
					["Rapidity"] = "Prędkość",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Ładowność",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Zręczność",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Mapa drogowa mistrzostwa",
					["Rookie"] = "Żółtodziób",
					["Middle"] = "Środek",
					["Advance"] = "Zaawansowany",
					["Pro"] = "Zawodowiec",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Zablokowany",
					["Approve"] = "Zatwierdzić",
					["Defer"] = "Odroczenie",
					["Train to Level Up"] = "Trenuj, aby awansować",
					["Unlock Higher Grade"] = "Odblokowanie wyższego poziomu",
					["Show head gauge"] = "Pokaż skrajnię nad głową",
					["Upgrade warning"] = "Czy awansowałbyś {0}\ndo klasy {1}?\n\nBędzie on jeszcze bardziej wydajny ale\njego dzienne wynagrodzenie wzrośnie do {2}</size>.",
					["NO CASHIERS HIRED"] = "NIE ZATRUDNIONO KASJERÓW",
					["NO RESTOCKERS HIRED"] = "NIE ZATRUDNIONO MAGAZYNIERÓW",
					["NO CUSTOMER HELPERS HIRED"] = "NIE ZATRUDNIONO WSPARCIA KLIENTA",
					["NO SECURITY GUARDS HIRED"] = "NIE ZATRUDNIONO PRACOWNIKÓW OCHRONY",
					["NO JANITORS HIRED"] = "NIE ZATRUDNIONO SPRZĄTACZY",
				},
				new Localizations("nl-NL") { // オランダ
					["Cashier Name"] = "Kassier {0}",
					["Restocker Name"] = "Vakkenvuller {0}",
					["Customer Helper Name"] = "Klantenhulp {0}",
					["Security Guard Name"] = "Beveiliger {0}",
					["Janitor Name"] = "Schoonmaker {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["Level"] = "Niveau {0} - {1}",
					["TRAINING"] = "Opleiding",
					["Cashiers"] = "Cassières",
					["Restockers"] = "<size=80%>Vakkenvullers</size>",
					["Customer Helpers"] = "<size=90%>Klantenhulp</size>",
					["Security Guards"] = "Beveiligers",
					["Janitors"] = "<size=80%>Schoonmakers</size>",
					["Exp."] = "EXP",
					["Scans Per Minute"] = "Scans per minuut",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Betalingstijd",
					["Payment Time Sec."] = "{0} sec.",
					["Daily Wage"] = "Dagloon",
					["Rapidity"] = "Vlugheid",
					["Speed"] = "{0}<size=70%> km/u</size>",
					["Capacity"] = "Laadcapaciteit",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Handigheid",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Meesterschap stappenplan",
					["Rookie"] = "Beginner",
					["Middle"] = "Midden",
					["Advance"] = "Gevorderd",
					["Pro"] = "Pro",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Gesloten",
					["Approve"] = "Goedkeuren",
					["Defer"] = "Uitstellen",
					["Train to Level Up"] = "Train om omhoog te komen",
					["Unlock Higher Grade"] = "Hogere rang vrijspelen",
					["Show head gauge"] = "Toon het bovenleidingsprofiel",
					["Upgrade warning"] = "Zou je kassier {0} promoveren\nnaar de {1}-rang?\n\nHij zal nog efficiënter zijn maar\nzijn dagloon zal VERHOGEN naar {2}</size>.",
					["NO CASHIERS HIRED"] = "GEEN KASSIERS AANGENOMEN",
					["NO RESTOCKERS HIRED"] = "GEEN VAKKENVULLERS AANGENOMEN",
					["NO CUSTOMER HELPERS HIRED"] = "GEEN KLANTENHELPERS AANGENOMEN",
					["NO SECURITY GUARDS HIRED"] = "GEEN BEVEILIGERS AANGENOMEN",
					["NO JANITORS HIRED"] = "GEEN CONCIËRGES AANGENOMEN",
				},
				new Localizations("es-ES") { // スペイン
					["Cashier Name"] = "Cajero {0}",
					["Restocker Name"] = "Reponedor {0}",
					["Customer Helper Name"] = "Asistente de Venta {0}",
					["Security Guard Name"] = "Guardia de seguridad {0}",
					["Janitor Name"] = "Conserje {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["Level"] = "Livello {0} - {1}",
					["TRAINING"] = "Formación",
					["Cashiers"] = "Cajeros",
					["Restockers"] = "<size=90%>Reponedores</size>",
					["Customer Helpers"] = "<size=80%>Asistente de\nVenta</size>",
					["Security Guards"] = "<size=80%>Vigilantes de\nseguridad</size>",
					["Janitors"] = "Conserjes",
					["Exp."] = "EXP",
					["Scans Per Minute"] = "Escaneos por minuto",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Tiempo de pago",
					["Payment Time Sec."] = "{0} seg.",
					["Daily Wage"] = "Salario diario",
					["Rapidity"] = "Rapidez",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Capacidad de carga",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Destreza",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Hoja de ruta de maestría",
					["Rookie"] = "Novato",
					["Middle"] = "Medio",
					["Advance"] = "Avanzar",
					["Pro"] = "Pro",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Bloqueado",
					["Approve"] = "Aprobar",
					["Defer"] = "Aplazar",
					["Train to Level Up"] = "Entrenar para subir de nivel",
					["Unlock Higher Grade"] = "Desbloquear grado superior",
					["Show head gauge"] = "Mostrar el gálibo superior",
					["Upgrade warning"] = "¿Ascenderías a {0}\nal grado {1}?\n\n Será aún más eficiente pero\nsu salario diario AUMENTARÁ a {2}</size>.",
					["NO CASHIERS HIRED"] = "NO HAY CAJEROS CONTRATADOS",
					["NO RESTOCKERS HIRED"] = "NO HAY REPONEDORES CONTRATADOS",
					["NO CUSTOMER HELPERS HIRED"] = "NO HAY AYUDANTES DEL CLIENTE CONTRATADOS",
					["NO SECURITY GUARDS HIRED"] = "NO HAY GUARDIAS DE SEGURIDAD CONTRATADOS",
					["NO JANITORS HIRED"] = "NO HAY CONSERJES CONTRATADOS",
				},
				new Localizations("tr") { // トルコ
					["Cashier Name"] = "Kasiyer {0}",
					["Restocker Name"] = "Depo Görevlisi {0}",
					["Customer Helper Name"] = "Müsteri Yardımcısı {0}",
					["Security Guard Name"] = "Güvenlik Görevlisi {0}",
					["Janitor Name"] = "Temizlikci {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["Level"] = "{0}. Seviye - {1}",
					["TRAINING"] = "EĞİTİM",
					["Cashiers"] = "Kasiyerler",
					["Restockers"] = "<size=80%>Depo\nGörevlileri</size>",
					["Customer Helpers"] = "<size=80%>Müsteri\nYardımcıları</size>",
					["Security Guards"] = "<size=80%>Güvenlik\nGörevlileri</size>",
					["Janitors"] = "<size=95%>Temizlikciler</size>",
					["Exp."] = "EXP",
					["Scans Per Minute"] = "Dakika başına tarama",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Ödeme süresi",
					["Payment Time Sec."] = "{0} saniye.",
					["Daily Wage"] = "Günlük ücret",
					["Rapidity"] = "Hızlılık",
					["Speed"] = "{0}<size=70%> km/s</size>",
					["Capacity"] = "Kapasite",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "El becerisi",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Ustalık yol haritası",
					["Rookie"] = "Çaylak",
					["Middle"] = "Orta",
					["Advance"] = "İlerleme",
					["Pro"] = "Pro",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Kilitli",
					["Approve"] = "Onaylamak",
					["Defer"] = "Erteleme",
					["Train to Level Up"] = "Seviye atlamak için eğitin",
					["Unlock Higher Grade"] = "Üst sınıfın kilidini aç",
					["Show head gauge"] = "Göstergeyi başınızın üzerinde gösterin",
					["Upgrade warning"] = "{0}'i {1} sınıfına terfi\nettirir misiniz?\n\nDaha da verimli olacaktır ama\ngünlük ücreti {2}</size> yükselecektir.",
					["NO CASHIERS HIRED"] = "KASIYER IŞE ALINMADI",
					["NO RESTOCKERS HIRED"] = "DEPO GÖREVLİ IŞE ALINMADI",
					["NO CUSTOMER HELPERS HIRED"] = "MÜSTERİ YARDIMCILARI IŞE ALINMADI",
					["NO SECURITY GUARDS HIRED"] = "GÜVENLİK GÖREVLİLERİ IŞE ALINMADI",
					["NO JANITORS HIRED"] = "TEMİZLİKÇİLER IŞE ALINMADI",
				},
				new Localizations("zh-CN") { // 簡体
					["Cashier Name"] = "收银员 {0}",
					["Restocker Name"] = "补货员 {0}",
					["Customer Helper Name"] = "客户助理 {0}",
					["Security Guard Name"] = "警卫 {0}",
					["Janitor Name"] = "清洁工 {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["Level"] = "{0} 级 - {1}",
					["TRAINING"] = "训练",
					["Cashiers"] = "收银员",
					["Restockers"] = "补货者",
					["Customer Helpers"] = "客户帮手",
					["Security Guards"] = "保安人员",
					["Janitors"] = "清洁工们",
					["Exp."] = "EXP",
					["Scans Per Minute"] = "每分钟扫描次数",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "付款时间",
					["Payment Time Sec."] = "{0} 秒",
					["Daily Wage"] = "每日工资",
					["Rapidity"] = "敏捷性",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "装载能力",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "灵巧性",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "精通路线图",
					["Rookie"] = "新手",
					["Middle"] = "中级",
					["Advance"] = "高级",
					["Pro"] = "专业职",
					["Ninja"] = "忍者",
					["?"] = "?",
					["Locked"] = "锁定",
					["Approve"] = "批准",
					["Defer"] = "推迟",
					["Train to Level Up"] = "训练直到你升级",
					["Unlock Higher Grade"] = "解锁更高等级",
					["Show head gauge"] = "在头部上方显示仪表",
					["Upgrade warning"] = "您会将 {0} 提升为“{1}”别吗？\n\n他的效率会更高，但日薪也会增加到 {2}</size>。",
					["NO CASHIERS HIRED"] = "没有雇用收银员",
					["NO RESTOCKERS HIRED"] = "没有雇用补货员",
					["NO CUSTOMER HELPERS HIRED"] = "没有雇用客户助理",
					["NO SECURITY GUARDS HIRED"] = "没有雇用警卫",
					["NO JANITORS HIRED"] = "没有雇用清洁工",
				},
				new Localizations("zh-TW") { // 繁体
					["Cashier Name"] = "收銀員 {0}",
					["Restocker Name"] = "補貨員 {0}",
					["Customer Helper Name"] = "客戶幫手 {0}",
					["Security Guard Name"] = "保安員 {0}",
					["Janitor Name"] = "清潔員 {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["Level"] = "{0} 級 - {1}",
					["TRAINING"] = "訓練",
					["Cashiers"] = "收銀員",
					["Restockers"] = "補貨員",
					["Customer Helpers"] = "客戶幫手",
					["Security Guards"] = "保安員",
					["Janitors"] = "清潔員",
					["Exp."] = "EXP",
					["Scans Per Minute"] = "每分鐘掃描次數",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "付款時間",
					["Payment Time Sec."] = "{0} 秒",
					["Daily Wage"] = "每日工資",
					["Rapidity"] = "敏捷性",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "裝載能力",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "靈巧",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "精通路線圖",
					["Rookie"] = "新人",
					["Middle"] = "中級",
					["Advance"] = "高級",
					["Pro"] = "專業級",
					["Ninja"] = "忍者",
					["?"] = "？",
					["Locked"] = "鎖定",
					["Approve"] = "核准",
					["Defer"] = "推遲",
					["Train to Level Up"] = "訓練直到你升級",
					["Unlock Higher Grade"] = "解鎖更高等級",
					["Show head gauge"] = "在頭部上方顯示儀表",
					["Upgrade warning"] = "您會將 {0} 提升為“{1}”嗎？\n\n效率會更高，但日薪將增加至 {2}</size>。",
					["NO CASHIERS HIRED"] = "沒有僱用收銀員",
					["NO RESTOCKERS HIRED"] = "沒有僱用補貨員",
					["NO CUSTOMER HELPERS HIRED"] = "沒有僱用客戶幫手",
					["NO SECURITY GUARDS HIRED"] = "沒有僱用保安員",
					["NO JANITORS HIRED"] = "沒有僱用清潔員",
				},
				new Localizations("ko-KR") { // 韓国
					["Cashier Name"] = "계산원 {0}",
					["Restocker Name"] = "재입고 {0}",
					["Customer Helper Name"] = "고객 도우미 {0}",
					["Security Guard Name"] = "경비원 {0}",
					["Janitor Name"] = "청소부 {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["Level"] = "레벨 {0} - {1}",
					["TRAINING"] = "훈련",
					["Cashiers"] = "계산원",
					["Restockers"] = "재입고자",
					["Customer Helpers"] = "고객 도우미",
					["Security Guards"] = "경비원",
					["Janitors"] = "청소부들",
					["Exp."] = "EXP",
					["Scans Per Minute"] = "분당 스캔 수",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "결제 시간",
					["Payment Time Sec."] = "{0}초",
					["Daily Wage"] = "일일 임금",
					["Rapidity"] = "신속성",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "적재량",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "민첩성",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "마스터리 로드맵",
					["Rookie"] = "루키",
					["Middle"] = "중급",
					["Advance"] = "고급",
					["Pro"] = "프로",
					["Ninja"] = "닌자",
					["?"] = "?",
					["Locked"] = "잠김",
					["Approve"] = "승인",
					["Defer"] = "보류",
					["Train to Level Up"] = "레벨 업 훈련",
					["Unlock Higher Grade"] = "상위 등급 잠금 해제",
					["Show head gauge"] = "머리 위로 게이지 표시",
					["Upgrade warning"] = "{0} 을 『{1} 등급으』로 승격하시겠습니까?\n\n훨씬 더 효율적이겠지만\n일일 임금은 {2}</size>로 인상됩니다.",
					["NO CASHIERS HIRED"] = "고용된 계산원 없음",
					["NO RESTOCKERS HIRED"] = "고용된 재입고 없음",
					["NO CUSTOMER HELPERS HIRED"] = "고용된 고객 도우미 없음",
					["NO SECURITY GUARDS HIRED"] = "고용된 경비원 없음",
					["NO JANITORS HIRED"] = "고용된 청소부 없음",
				},
				new Localizations("ru-RU") { // ロシア
					["Cashier Name"] = "Кассир {0}",
					["Restocker Name"] = "Кладовщик {0}",
					["Customer Helper Name"] = "Консультант {0}",
					["Security Guard Name"] = "Охранник {0}",
					["Janitor Name"] = "Уборщик {0}",
					["Lvl"] = "<size=70%>Ур </size>{0}",
					["Popup Exp"] = "{0} ОП",
					["Level"] = "Уровень {0} - {1}",
					["TRAINING"] = "ОБУЧЕНИЕ",
					["Cashiers"] = "Кассиры",
					["Restockers"] = "<size=85%>Кладовщики</size>",
					["Customer Helpers"] = "<size=80%>Консультанты</size>",
					["Security Guards"] = "Охранники",
					["Janitors"] = "Уборщики",
					["Exp."] = "ОП",
					["Scans Per Minute"] = "Сканирование в минуту",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Время оплаты",
					["Payment Time Sec."] = "{0} сек.",
					["Daily Wage"] = "Ежедневная зарплата",
					["Rapidity"] = "Быстрота",
					["Speed"] = "{0}<size=70%> км/ч</size>",
					["Capacity"] = "Грузоподъемность",
					["Weight/Height"] = "{0}<size=70%> кг</size> / {1}<size=70%> м</size>",
					["Dexterity"] = "Ловкость",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Дорожная карта мастерства",
					["Rookie"] = "Новичок",
					["Middle"] = "Средний",
					["Advance"] = "Продвинутый",
					["Pro"] = "Профи",
					["Ninja"] = "Ниндзя",
					["?"] = "?",
					["Locked"] = "Заперто",
					["Approve"] = "Одобрить",
					["Defer"] = "Отложить",
					["Train to Level Up"] = "Уровень повышен",
					["Unlock Higher Grade"] = "Улучшать",
					["Show head gauge"] = "Показать датчик на голове",
					["Upgrade warning"] = "Повысили бы вы {0}\nдо класса {1}?\n\nОн будет работать еще эффективнее но\nего дневная зарплата увеличится до {2}</size>.",
					["NO CASHIERS HIRED"] = "КАССИРЫ НЕ НАНЯТЫ",
					["NO RESTOCKERS HIRED"] = "КЛАДОВЩИКИ НЕ НАНЯТЫ",
					["NO CUSTOMER HELPERS HIRED"] = "ПОМОЩНИКИ КЛИЕНТОВ НЕ НАНЯТЫ",
					["NO SECURITY GUARDS HIRED"] = "ОХРАННИКИ НЕ НАНЯТЫ",
					["NO JANITORS HIRED"] = "УБОРЩИКИ НЕ НАНЯТЫ",
				},
				new Localizations("cs-CZ") { // チェコ
					["Cashier Name"] = "Pokladní {0}",
					["Restocker Name"] = "Doplňovač {0}",
					["Customer Helper Name"] = "Pomocník zákazníka {0}",
					["Security Guard Name"] = "Ostraha {0}",
					["Janitor Name"] = "Uklízeč {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["Level"] = "Úroveň {0} - {1}",
					["TRAINING"] = "ŠKOLENÍ",
					["Cashiers"] = "Pokladní",
					["Restockers"] = "Doplňovači",
					["Customer Helpers"] = "<size=80%>Pomocníci\nzákazníků</size>",
					["Security Guards"] = "Ostraha",
					["Janitors"] = "Údržba",
					["Exp."] = "EXP",
					["Scans Per Minute"] = "Skenování za minutu",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Doba platby",
					["Payment Time Sec."] = "{0} sek.",
					["Daily Wage"] = "Denní mzda",
					["Rapidity"] = "Rychlost",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Nosnost",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Obratnost",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Plán mistrovství",
					["Rookie"] = "Nováček",
					["Middle"] = "Střední",
					["Advance"] = "Pokročilý",
					["Pro"] = "Pro",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Zamčeno",
					["Approve"] = "Schválit",
					["Defer"] = "Odložit",
					["Train to Level Up"] = "Trénink pro zvýšení úrovně",
					["Unlock Higher Grade"] = "Odemknout vyšší úroveň",
					["Show head gauge"] = "Zobrazit měřič nad hlavou",
					["Upgrade warning"] = "Chcete povýšit {0}\nna úroveň {1}?\n\nBude efektivnější ale\njeho denní mzda se ZVÝŠÍ na {2}</size>.",
					["NO CASHIERS HIRED"] = "ŽÁDNÍ POKLADNÍ NEBYLI NAJATI",
					["NO RESTOCKERS HIRED"] = "ŽÁDNÍ DOPLŇOVAČI NEBYLI NAJATI",
					["NO CUSTOMER HELPERS HIRED"] = "ŽÁDNÍ POMOCNÍCI ZÁKAZNÍKŮ NEBYLI NAJATI",
					["NO SECURITY GUARDS HIRED"] = "ŽÁDNÁ OSTRAHA NEBYLA NAJATA",
					["NO JANITORS HIRED"] = "ŽÁDNÁ ÚDRŽBA NEBYLA NAJATA",
				},
				new Localizations("fi-FI") { // フィンランド
					["Cashier Name"] = "Myyjä {0}",
					["Restocker Name"] = "Hyllyttäjä {0}",
					["Customer Helper Name"] = "Asiakaspalvelija {0}",
					["Security Guard Name"] = "Vartija {0}",
					["Janitor Name"] = "Siivooja {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["Level"] = "Taso {0} - {1}",
					["TRAINING"] = "Koulutus",
					["Cashiers"] = "Myyjät",
					["Restockers"] = "Hyllyttäjät",
					["Customer Helpers"] = "<size=80%>Asiakas-\npalvelijat</size>",
					["Security Guards"] = "Vartijat",
					["Janitors"] = "Siivoojat",
					["Exp."] = "EXP",
					["Scans Per Minute"] = "Skannauksia minuutissa",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Maksun kesto",
					["Payment Time Sec."] = "{0} sek.",
					["Daily Wage"] = "Päiväpalkka",
					["Rapidity"] = "Nopeus",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Kapasiteetti",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Näppäryys",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Edistyksen tiekartta",
					["Rookie"] = "Alokas",
					["Middle"] = "Keskitaso",
					["Advance"] = "Edistynyt",
					["Pro"] = "Ammatti",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Lukittu",
					["Approve"] = "Hyväksyä",
					["Defer"] = "Lykkää",
					["Train to Level Up"] = "Kouluttaudu tasolle",
					["Unlock Higher Grade"] = "Avaa korkeampi luokka",
					["Show head gauge"] = "Näytä mittari pään ylle",
					["Upgrade warning"] = "Edistäisitkö {0}:n\nluokkaan {1}?\n\nSe on entistäkin tehokkaampi mutta\nsen päiväpalkka KASVAA {2}</size>.",
					["NO CASHIERS HIRED"] = "EI MYYJIÄ PALKATTU",
					["NO RESTOCKERS HIRED"] = "EI HYLLYTTÄJIÄ PALKATTU",
					["NO CUSTOMER HELPERS HIRED"] = "EI ASIAKASPALVELIJIA PALKATTU",
					["NO SECURITY GUARDS HIRED"] = "EI VARTIJIA PALKATTU",
					["NO JANITORS HIRED"] = "EI SIIVOOJIA PALKATTU",
				},
				new Localizations("hu-HU") { // ハンガリー
					["Cashier Name"] = "Pénztáros {0}",
					["Restocker Name"] = "Árufeltöltő {0}",
					["Customer Helper Name"] = "Vásárlóassezisztens {0}",
					["Security Guard Name"] = "Biztonsági őr {0}",
					["Janitor Name"] = "Takarító {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["TRAINING"] = "Képzés",
					["Cashiers"] = "<size=95%>Pénztárosok</size>",
					["Restockers"] = "<size=90%>Árufeltöltők</size>",
					["Customer Helpers"] = "<size=80%>Vásárló-\nasszisztens</size>",
					["Security Guards"] = "<size=80%>Biztonsági\nőrök</size>",
					["Janitors"] = "Takarítók",
					["Exp."] = "EXP",
					["Level"] = "Szint {0} - {1}",
					["Scans Per Minute"] = "Szkennelések percenként",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Fizetési idő",
					["Payment Time Sec."] = "{0} mp",
					["Daily Wage"] = "Napi bér",
					["Rapidity"] = "Gyorsaság",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Terhelhetőség",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Ügyesség",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Mesterség térkép",
					["Rookie"] = "Újonc",
					["Middle"] = "Középhaladó",
					["Advance"] = "Haladó",
					["Pro"] = "Profi",
					["Ninja"] = "Nindzsa",
					["?"] = "?",
					["Locked"] = "Zárolva",
					["Approve"] = "Jóváhagy",
					["Defer"] = "Elhalaszt",
					["Train to Level Up"] = "Képzés szintlépéshez",
					["Unlock Higher Grade"] = "Magasabb szint feloldása",
					["Show head gauge"] = "Fej feletti mérő mutatása",
					["Upgrade warning"] = "Előlépteti {0}-t\na(z) {1} szintre?\n\nHatékonyabb lesz de\na napi bére MEGNŐ {2}</size>-ra/re.",
					["NO CASHIERS HIRED"] = "NINCS FELVETT PÉNZTÁROS",
					["NO RESTOCKERS HIRED"] = "NINCS FELVETT ÁRFELTÖLTŐ",
					["NO CUSTOMER HELPERS HIRED"] = "NINCS FELVETT VÁSÁRLÓASSEZISZTENS",
					["NO SECURITY GUARDS HIRED"] = "NINCS FELVETT BIZTONSÁGI ŐR",
					["NO JANITORS HIRED"] = "NINCS FELVETT TAKARÍTÓ",
				},
				new Localizations("lt-LT") { // リトアニア
					["Cashier Name"] = "Kasininkas {0}",
					["Restocker Name"] = "Salės darbuotojas {0}",
					["Customer Helper Name"] = "Klientų pagalbininkas {0}",
					["Security Guard Name"] = "Apsaugos darbuotojas {0}",
					["Janitor Name"] = "Sargas {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["TRAINING"] = "Mokymai",
					["Cashiers"] = "Kasininkai",
					["Restockers"] = "<size=80%>Salės\ndarbuotojai</size>",
					["Customer Helpers"] = "<size=80%>Klientų\npagalbininkai</size>",
					["Security Guards"] = "<size=80%>Apsaugos\ndarbuotojai</size>",
					["Janitors"] = "Sargybiniai",
					["Exp."] = "EXP",
					["Level"] = "Lygis {0} - {1}",
					["Scans Per Minute"] = "Skenavimai per minutę",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Apmokėjimo laikas",
					["Payment Time Sec."] = "{0} sek.",
					["Daily Wage"] = "Dienos atlyginimas",
					["Rapidity"] = "Greitis",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Talpa",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Vikrumas",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Meistriškumo planas",
					["Rookie"] = "Naujokas",
					["Middle"] = "Vidutinis",
					["Advance"] = "Pažengęs",
					["Pro"] = "Pro",
					["Ninja"] = "Nindzė",
					["?"] = "?",
					["Locked"] = "Užrakinta",
					["Approve"] = "Patvirtinti",
					["Defer"] = "Atidėti",
					["Train to Level Up"] = "Traukinys kelti lygį",
					["Unlock Higher Grade"] = "Atrakinti aukštesnį lygį",
					["Show head gauge"] = "Rodyti matuoklį virš galvos",
					["Upgrade warning"] = "Ar norite paaukštinti {0}\nį {1} lygį?\n\nJis bus dar efektyvesnis,\nbet dienos atlyginimas padidės iki {2}</size>.",
					["NO CASHIERS HIRED"] = "NESAMDOMI KASININKAI",
					["NO RESTOCKERS HIRED"] = "NESAMDOMI SALĖS DARBUOTOJAI",
					["NO CUSTOMER HELPERS HIRED"] = "NESAMDOMI KLIENTŲ PAGALBININKAI",
					["NO SECURITY GUARDS HIRED"] = "NESAMDOMI APSAUGOS DARBUOTOJAI",
					["NO JANITORS HIRED"] = "NESAMDOMI SARGYBINIAI",
				},
				
				new Localizations("ro-RO") { // ルーマニア
					["Cashier Name"] = "Casier {0}",
					["Restocker Name"] = "Angajat realimentare {0}",
					["Customer Helper Name"] = "Asistent pentru clienți {0}",
					["Security Guard Name"] = "Paznic {0}",
					["Janitor Name"] = "Om de serviciu {0}",
					["Lvl"] = "<size=70%>Lv </size>{0}",
					["Popup Exp"] = "{0} EXP",
					["TRAINING"] = "Îndrumare",
					["Cashiers"] = "Casieri",
					["Restockers"] = "<size=80%>Reapro-\nbizionatori</size>",
					["Customer Helpers"] = "<size=80%>Ajutor Clienți</size>",
					["Security Guards"] = "Paznici",
					["Janitors"] = "<size=80%>Oameni de\nserviciu</size>",
					["Exp."] = "EXP",
					["Level"] = "Nivel {0} - {1}",
					["Scans Per Minute"] = "Scanări pe minut",
					["SPM Range"] = "{0} - {1}",
					["Payment Time"] = "Timp de plată",
					["Payment Time Sec."] = "{0} sec.",
					["Daily Wage"] = "Salariu zilnic",
					["Rapidity"] = "Rapiditate",
					["Speed"] = "{0}<size=70%> km/h</size>",
					["Capacity"] = "Capacitate",
					["Weight/Height"] = "{0}<size=70%> kg</size> / {1}<size=70%> m</size>",
					["Dexterity"] = "Dexteritate",
					["Percentage"] = "{0}<size=70%>%</size>",
					["Mastery Roadmap"] = "Foaie de parcurs pentru progres",
					["Rookie"] = "Începător",
					["Middle"] = "Intermediar",
					["Advance"] = "Avansat",
					["Pro"] = "Pro",
					["Ninja"] = "Ninja",
					["?"] = "?",
					["Locked"] = "Blocat",
					["Approve"] = "Aprobat",
					["Defer"] = "Amânat",
					["Train to Level Up"] = "Antrenează-te la nivel superior",
					["Unlock Higher Grade"] = "Deblocați un grad superior",
					["Show head gauge"] = "Arată indicatorul deasupra capului",
					["Upgrade warning"] = "Doriți să promovați {0}\nla gradul {1}?\n\nVa fi și mai eficient dar\nsalariul său zilnic va CREȘTE la {2}</size>.",
					["NO CASHIERS HIRED"] = "NU SUNT ANGAJAȚI CASIERI",
					["NO RESTOCKERS HIRED"] = "NU SUNT ANGAJAȚI REAPROVIZIONATORI",
					["NO CUSTOMER HELPERS HIRED"] = "NU SUNT ANGAJAȚI AJUTOR CLIENȚI",
					["NO SECURITY GUARDS HIRED"] = "NU SUNT ANGAJAȚI PAZNICI",
					["NO JANITORS HIRED"] = "NU SUNT ANGAJAȚI OAMENI DE SERVICIU",	
				},
			};

			if (settings.CustomizeLocalization) {
                Write(langs);
			}
			return langs;
		}
	}

}